apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: databases
spec:
  schedule: "@weekly"
  backupOwnerReference: self
  cluster:
    name: postgres
