keys:
  - &dh274 age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
  - &k3s-flux-operator-dev age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47

creation_rules:
  # Default rule for all SOPS files - encrypts data and stringData fields
  - encrypted_regex: '^(data|stringData)$'
    key_groups:
    - age:
      - *dh274
      - *k3s-flux-operator-dev

  # Flux specific rules for components directory
  - path_regex: components/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
    - age:
      - *dh274
      - *k3s-flux-operator-dev

  # Flux specific rules for cluster directory
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
    - age:
      - *dh274
      - *k3s-flux-operator-dev

