---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-db
  namespace: automation
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB

  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant
      secret:
        name: home-assistant-db-secret
