apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secret
    namespace: automation
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MrmFSvPExsy6WcLC0A==,iv:7Gm8vyRKHOGswBElbEtQWIBvtMUaOZE3/7h816c7aGM=,tag:0ATC8KO1yU7UPnBEKZSAKA==,type:str]
    password: ENC[AES256_GCM,data:5xIcmOIWZ9XSEkLMnJskNVRRn2gknkLojMduu/Z2Mw==,iv:rUO3nea2hjvFlsKKleMq5o7GDXPOtPK4doOPBoDL6Qc=,tag:3FTLGoQoHx1IXsSUFHmYVQ==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzA1a1VJWWlUVGxYdDMy
            RDNYY3NLT3dsWWNpdldNK2tTMUNtbXFWQWc0Ci9NdEcvanFXMGE2YXF5OFU3RStU
            cjZJMmtRdXNRV3hXY3JVMkl3amsweVkKLS0tIDVxY0JlTFd0bW1xK3lFbTZQa213
            VzdZYjUvRC95QzdYdnRrNUVmbGwxaHMK8XahLimDXboZkOS693Y4CvBqiKQGM0x6
            8zdjRJrRIPDFSfWglRUxgGHyJlbyY8fYeicAaXBVi0XmNxLyCoh+vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1IyaDlEYWp1UlBLTEYz
            cGhReTEwNmR1bDIrNk9VMXY2OVRUaEdVaFZzCnUrZm1FUlV4dU9Qd25GekN0UENJ
            a0poMzUxOU4waVZ6dEhKaFE1Y0tNZ2cKLS0tIERXeUVwWDRPNzh0dERZcjBlQzVv
            ZE1Tb2YvZHU2ODdQeTVMYmUreGNJTkEK2pbDJkGEmkHaMEFI2ngRPvf21n5zlKLj
            pCfE0y/8+RmpJbm3DwkbnSWpXgIr7yGEY9Qzprih+IinxmeJ+awgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T15:53:08Z"
    mac: ENC[AES256_GCM,data:OfXNKCriwxzjZU3XojhTpRDNik/CUhFUB8cv5QgB/SC4/U0xtOJ+AFuoLOe/RZ13JzyiKlom/pPRd37AFShM8DqzVGZFLSUE2+Pns0thbvLXs5yLOLQkcvuWiAVumrz3tG9zdsdl9ro/vcOUEX3O/aAicZ8KONEEzdG4ojUXQDc=,iv:zkX89bdSevSVBgK1NFdpINGTHUsTvLcWLatDMJ9yF6Q=,tag:mjMPK/QEz/cELmTWVSXIsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-backup-secret
    namespace: automation
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:et2k7jQkDsAH7oYL33bLSO8RTZ5Cg0G5qg==,iv:2mvmKLvIy1WPCOXTrNmBMk62jj6p0A+woLt7QpnJ0I8=,tag:geHuVIkFBmWgt4JurKoo2g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DwolPr/vsci2MTaSVcM87xvJCHscl8UPuQ==,iv:MaSOuyY9r4zp6+0X4cFsS4MiAzNyLHcEBBljFiczxus=,tag:pfvvf/JjHCzBHjMr+t5Z4w==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzA1a1VJWWlUVGxYdDMy
            RDNYY3NLT3dsWWNpdldNK2tTMUNtbXFWQWc0Ci9NdEcvanFXMGE2YXF5OFU3RStU
            cjZJMmtRdXNRV3hXY3JVMkl3amsweVkKLS0tIDVxY0JlTFd0bW1xK3lFbTZQa213
            VzdZYjUvRC95QzdYdnRrNUVmbGwxaHMK8XahLimDXboZkOS693Y4CvBqiKQGM0x6
            8zdjRJrRIPDFSfWglRUxgGHyJlbyY8fYeicAaXBVi0XmNxLyCoh+vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1IyaDlEYWp1UlBLTEYz
            cGhReTEwNmR1bDIrNk9VMXY2OVRUaEdVaFZzCnUrZm1FUlV4dU9Qd25GekN0UENJ
            a0poMzUxOU4waVZ6dEhKaFE1Y0tNZ2cKLS0tIERXeUVwWDRPNzh0dERZcjBlQzVv
            ZE1Tb2YvZHU2ODdQeTVMYmUreGNJTkEK2pbDJkGEmkHaMEFI2ngRPvf21n5zlKLj
            pCfE0y/8+RmpJbm3DwkbnSWpXgIr7yGEY9Qzprih+IinxmeJ+awgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T15:53:08Z"
    mac: ENC[AES256_GCM,data:OfXNKCriwxzjZU3XojhTpRDNik/CUhFUB8cv5QgB/SC4/U0xtOJ+AFuoLOe/RZ13JzyiKlom/pPRd37AFShM8DqzVGZFLSUE2+Pns0thbvLXs5yLOLQkcvuWiAVumrz3tG9zdsdl9ro/vcOUEX3O/aAicZ8KONEEzdG4ojUXQDc=,iv:zkX89bdSevSVBgK1NFdpINGTHUsTvLcWLatDMJ9yF6Q=,tag:mjMPK/QEz/cELmTWVSXIsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: git-ssh-keys
    namespace: automation
type: Opaque
stringData:
    id_rsa: ENC[AES256_GCM,data:3a9z4Wp5xiE3OySPwXNgc4kFeVc+O9m9jRWrsIEYOMbUM1ucxlkFobaLC34nXYTDaG7kX3a3nJ2o7aZlCCGFGL/QkWGP0NMs/YM6SpztjZ635cLTPgaCdt4wlRkU3D8=,iv:15Mogzyu4jFXkggjSt8tA+zuZIQuH5q0hqY6fBpXVFs=,tag:DpoXjXAnvHIbyfhXPvGBQA==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzA1a1VJWWlUVGxYdDMy
            RDNYY3NLT3dsWWNpdldNK2tTMUNtbXFWQWc0Ci9NdEcvanFXMGE2YXF5OFU3RStU
            cjZJMmtRdXNRV3hXY3JVMkl3amsweVkKLS0tIDVxY0JlTFd0bW1xK3lFbTZQa213
            VzdZYjUvRC95QzdYdnRrNUVmbGwxaHMK8XahLimDXboZkOS693Y4CvBqiKQGM0x6
            8zdjRJrRIPDFSfWglRUxgGHyJlbyY8fYeicAaXBVi0XmNxLyCoh+vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR1IyaDlEYWp1UlBLTEYz
            cGhReTEwNmR1bDIrNk9VMXY2OVRUaEdVaFZzCnUrZm1FUlV4dU9Qd25GekN0UENJ
            a0poMzUxOU4waVZ6dEhKaFE1Y0tNZ2cKLS0tIERXeUVwWDRPNzh0dERZcjBlQzVv
            ZE1Tb2YvZHU2ODdQeTVMYmUreGNJTkEK2pbDJkGEmkHaMEFI2ngRPvf21n5zlKLj
            pCfE0y/8+RmpJbm3DwkbnSWpXgIr7yGEY9Qzprih+IinxmeJ+awgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T15:53:08Z"
    mac: ENC[AES256_GCM,data:OfXNKCriwxzjZU3XojhTpRDNik/CUhFUB8cv5QgB/SC4/U0xtOJ+AFuoLOe/RZ13JzyiKlom/pPRd37AFShM8DqzVGZFLSUE2+Pns0thbvLXs5yLOLQkcvuWiAVumrz3tG9zdsdl9ro/vcOUEX3O/aAicZ8KONEEzdG4ojUXQDc=,iv:zkX89bdSevSVBgK1NFdpINGTHUsTvLcWLatDMJ9yF6Q=,tag:mjMPK/QEz/cELmTWVSXIsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
