# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cashless-server-secret
    namespace: utilities
stringData:
    PG_USER: ENC[AES256_GCM,data:2b3X,iv:Id4WAotLfBEdLmbXqZ0NuznA30emjqJ5Lohy89bUHgQ=,tag:f6hbd5lMSb+6wDOOxFZetA==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:8uqv7czyzTC8I/XKr89NIFWPw9kQJaTyd5I9rw1P6ak=,iv:dA+JHrFINhnjswRhDdk9Ze1EH1KM/atkLXDHMtcbGig=,tag:7zg+5g+A2Sg71a3JhlUycg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra2lTM2MyMzdMODRQeFF2
            TWNwOGtCSlQxNzJ2QURLTGNBNEFCeTFtREM4CmdQWUNsQ1Jna1lwR2ZrcXlSd21i
            d0FvQXVOOTRrakEvRlFEcktOZVd0WEUKLS0tIGtiNDc2WlpIeEl6MkxrY3cyQ3pq
            dGgyZHdyYXhmK1k2MlErdTQ0Z2tObHcKvIgYb7eWvf005uSWqa/rfB5EoFTs3wti
            k2UxWlZAi9H2VZc1Wpsgmmq9hAq3xVA/Cdq0HF9qjwUZrVY/gq17OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTm1XN1RuNTRBWUpNelhG
            ZDlLUExMaHIyS1VmZU0xNTZSckxVZ2swd2k4CkVUVmJubUVZdWZYMnlaRG1tb2VQ
            RWJqcWZ4Q3YyYlpydmNobVM4VEkwclEKLS0tIHpNVFBFUCtFYzBQOXVZS2tOaWpx
            dzJNMHo3eWZySWdTWmlXSFVuaUh4WW8K9DJuzMyFWEyvGjQRAhZ2YwAdpJ2u8RrD
            5s5XxgnF1zXdx6kD8cC/SDU4EhbvsLK0XkNA9FF24HxrxiHZuarZ2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYU44VkdPUnBPeGQ2bFRQ
            UWVrZG10V3RrbWxtTWVWTXZ4WlkzRHkrUUVRCngyZURPZXNybWJRWkVzM1hoTzBa
            dDdNZEVrTzFXK2hGeDZsNWU3dms5YkUKLS0tIFlOOFRmWURFU2dpRjZWckIyN2pK
            NTFVZUVVY0h2MitPTWQ4NDhuSDFyM0EKfxfOrpnIXAcmY75GpmiPCVhchfiROEwx
            4R+fLDrZrSzd0gGLW/HydEg41Ael1mOMo7epIk6M6EJ+OhkrwbP4WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y54qgey5kd66rtadzwck29pmu8dz78wgdymkcdf84kpprs5d634qwswgt7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-05-27T21:47:49Z"
    mac: ENC[AES256_GCM,data:9R18fEsLeFvW0Efio8yYXfpl8quBANEkfIeDzfvi1xu+IbyuqbzXIUqDQ1kRmCQuP3UCm3azF6XHLeAnJWG/EwJoDGhB2Sw4AG0Xd0PgoDzwGDpNG6/34E17d4w7G5L49TkKv55kLyWzpvqJwDrAtyLPo2E9r9bc6vDiBTvXcSM=,iv:mJIn/Oc5JE8vPrF8fwCMMUJA1oAiKC68W95yFnTV8E0=,tag:UiBIYqfDhx8FrSjJ0tZ+fw==,type:str]
    version: 3.9.0
