apiVersion: v1
kind: Secret
metadata:
    name: powerdns-postgres-secret
    namespace: networking
stringData:
    username: ENC[AES256_GCM,data:ymOhcC/XZM0=,iv:HvQaqwLM56mpHbMEHT0BASwEG4r1ODSWwR970PWM1QA=,tag:15KBscG+kE2e+dem1s86UA==,type:str]
    password: ENC[AES256_GCM,data:O/LGLKJkzsev/5v5XgLc4MIiZkEzl1dFLpo=,iv:nk2gjBnnmGm2j9zd+XToQ+oZPBU94EQ/KCwxaurSykk=,tag:reSuIZ6ZkCwjtJIhKET/oA==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVnVWd3RaN2IwQmdrencz
            VWpMRVlGTEVRQ2phL1AzVndYbENxeU1zYVRVCmpGWlo5VEtEbFRRcDFmcjB2RTdF
            OHhIK0k0KzNncDdtV2FpWnpMcE0xdjQKLS0tIDN4UG5CQ0x4dlo1Rm5INkR4NUFi
            RGVYWGxVLytUM2NkcnhkRTB4dnk1Z0kK592aBVRyiAW8QbS016eOaKKl7jCPqKRI
            cIhiJIk5qt5X3b1M9wCVeDBQNM+RWfBtSZcLpiU62I1rsERv5qf7iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGY0dERxL0l0b05SQ3B0
            M1ZaVzBiZVRBQjRSRzJQbk52aWt5T1dtRWc0Cm1lbEtCQ3ArYzVETVZlZkRta1VS
            ZFNHYzdmVzZXcGwxbDRLZHBJeUx0UUkKLS0tIFU2WDFJOWI4ZEg4OW1GZjFtSDdS
            bFBkY1VoK1lxS3dsTHhPRUNVTzlwS0UKuPFeYmL+n3rhVJrLuE5hosvykfArZeJZ
            4HbEgOTlCW+ZuTekg0D6f3inRORW7dIGEoE7O854BaQrWrvd/EDEDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T16:34:05Z"
    mac: ENC[AES256_GCM,data:Piqo4kJRD6sIYQF63TIGlgER8Uhv2ojCGvuwW4aF7C3lJzdNDFrISDEs3UhpD3YivDq1zpUOnd08OiNIRRYsEaygx+uZd///DOYo43yfsfUaQSSZyix742hu0THqIIaGNmicXgIaGtXVONX/fewoL5hvXnVvbWRFTMSfzKzllIk=,iv:Vo6ibempTNWe6LurgQD2Nnd+zrrWRbNBq9Pz9bIa1zk=,tag:jV7Lp1AoBa7PvPouoFgrqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: powerdns-api-secret
    namespace: networking
stringData:
    #ENC[AES256_GCM,data:pmPEGBEYo+qwV1rt3aqegbLj6vXJOhjre/XV4aXMBIEExiMtO4SN5A7axvHfeGAtLw==,iv:HL7VSMajh6npMDjzUrAgd4/cA/dTQdEB0TI3mx2eA/E=,tag:ZuvED+4TrqGVCrXyMXNpJg==,type:comment]
    api-key: ENC[AES256_GCM,data:AwKZPaGRzuZ2dOQW7D3wdg==,iv:X0OhnABZAjEmaEKKaY8fVUEuAH8cxbIVy+3z7yMGDjQ=,tag:ZT+QI8pJ4vD7+XvPmlaHfQ==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVnVWd3RaN2IwQmdrencz
            VWpMRVlGTEVRQ2phL1AzVndYbENxeU1zYVRVCmpGWlo5VEtEbFRRcDFmcjB2RTdF
            OHhIK0k0KzNncDdtV2FpWnpMcE0xdjQKLS0tIDN4UG5CQ0x4dlo1Rm5INkR4NUFi
            RGVYWGxVLytUM2NkcnhkRTB4dnk1Z0kK592aBVRyiAW8QbS016eOaKKl7jCPqKRI
            cIhiJIk5qt5X3b1M9wCVeDBQNM+RWfBtSZcLpiU62I1rsERv5qf7iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGY0dERxL0l0b05SQ3B0
            M1ZaVzBiZVRBQjRSRzJQbk52aWt5T1dtRWc0Cm1lbEtCQ3ArYzVETVZlZkRta1VS
            ZFNHYzdmVzZXcGwxbDRLZHBJeUx0UUkKLS0tIFU2WDFJOWI4ZEg4OW1GZjFtSDdS
            bFBkY1VoK1lxS3dsTHhPRUNVTzlwS0UKuPFeYmL+n3rhVJrLuE5hosvykfArZeJZ
            4HbEgOTlCW+ZuTekg0D6f3inRORW7dIGEoE7O854BaQrWrvd/EDEDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T16:34:05Z"
    mac: ENC[AES256_GCM,data:Piqo4kJRD6sIYQF63TIGlgER8Uhv2ojCGvuwW4aF7C3lJzdNDFrISDEs3UhpD3YivDq1zpUOnd08OiNIRRYsEaygx+uZd///DOYo43yfsfUaQSSZyix742hu0THqIIaGNmicXgIaGtXVONX/fewoL5hvXnVvbWRFTMSfzKzllIk=,iv:Vo6ibempTNWe6LurgQD2Nnd+zrrWRbNBq9Pz9bIa1zk=,tag:jV7Lp1AoBa7PvPouoFgrqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: powerdns-config-secrets
    namespace: networking
type: Opaque
stringData:
    credentials.conf: ENC[AES256_GCM,data:VIiDCmp3zABK9IE3kYUPWQcyA+JfVp65+PAwoOzIVMnpy27B56uUm7eDnOeu2HLGRytI5HNBCCW7DCgTrGq2sH+5heNCXf6JXuLnvVKGZ6t4fga+ORfs6Xd+2+bbbGkooYm4lp5Qi4pz+VA3ziNEU0sBNmSxhRw0XJC4Cw==,iv:7D3AHoP5TdKPbg/1xC1XFH0zdW4vnKOePgpd12E0m2M=,tag:hXINFEuV0yChzRO4tGg4gg==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVnVWd3RaN2IwQmdrencz
            VWpMRVlGTEVRQ2phL1AzVndYbENxeU1zYVRVCmpGWlo5VEtEbFRRcDFmcjB2RTdF
            OHhIK0k0KzNncDdtV2FpWnpMcE0xdjQKLS0tIDN4UG5CQ0x4dlo1Rm5INkR4NUFi
            RGVYWGxVLytUM2NkcnhkRTB4dnk1Z0kK592aBVRyiAW8QbS016eOaKKl7jCPqKRI
            cIhiJIk5qt5X3b1M9wCVeDBQNM+RWfBtSZcLpiU62I1rsERv5qf7iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGY0dERxL0l0b05SQ3B0
            M1ZaVzBiZVRBQjRSRzJQbk52aWt5T1dtRWc0Cm1lbEtCQ3ArYzVETVZlZkRta1VS
            ZFNHYzdmVzZXcGwxbDRLZHBJeUx0UUkKLS0tIFU2WDFJOWI4ZEg4OW1GZjFtSDdS
            bFBkY1VoK1lxS3dsTHhPRUNVTzlwS0UKuPFeYmL+n3rhVJrLuE5hosvykfArZeJZ
            4HbEgOTlCW+ZuTekg0D6f3inRORW7dIGEoE7O854BaQrWrvd/EDEDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T16:34:05Z"
    mac: ENC[AES256_GCM,data:Piqo4kJRD6sIYQF63TIGlgER8Uhv2ojCGvuwW4aF7C3lJzdNDFrISDEs3UhpD3YivDq1zpUOnd08OiNIRRYsEaygx+uZd///DOYo43yfsfUaQSSZyix742hu0THqIIaGNmicXgIaGtXVONX/fewoL5hvXnVvbWRFTMSfzKzllIk=,iv:Vo6ibempTNWe6LurgQD2Nnd+zrrWRbNBq9Pz9bIa1zk=,tag:jV7Lp1AoBa7PvPouoFgrqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
