---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: &name mopidy-data
    namespace: media
    labels:
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 10Gi
