---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  RURI_ADDR: "192.168.0.25"
  CLUSTER_EXTERNAL_SUBNET_PREFIX: 10.0.2
  CLUSTER_MACVLAN_HA: "10"
  CLUSTER_LB_HA: "50"
  FIX_EXTERNAL_IP: "10.0.2.1"
  CLUSTER_DOMAIN: "dev.example.com"
