apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_YT_API_KEY: ENC[AES256_GCM,data:cud83VUiDTn51IMfxQ57iEoOl1zrD4ONUErEULxgKpVP7a/1m9hY,iv:p6y4luubzoH44mDQL1eOeZf0ZZK1tZH382CMF7RUX9Q=,tag:D6knQx/w0Nrw1RrZqZWUuA==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:sgnv1+0wQm/tqz+QEVvH1No=,iv:2Q7xy04VeDuDCGHl7CWWdZPzsl1ej/0UgtGtPD9dKEI=,tag:48vMcEs3rcatTIpBeawXFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWjFhRmRHa2Z3SSt6SW81
            SlpJbkRubUxNWk5ZL3FBWUUrZUlaWmhsK1FZCjhmVkd3NnljZ1BqVWdhUDZhQ2F2
            V2h4REpRa1ZQdm1DSzFpQTRJS2tDdzQKLS0tIEVCY1BXdGduRXgySXUrbEJEam1S
            algxaFh4OExnQ3ZoV0ozRnBZaUJURTAKyp+UV9SzVRaG1Q/vL7CUbSd++pFSHWMW
            Z5XpAmMH35GXhamBZ0D0Rv713J2B5Q67BqfNbEJfshBc/bW+cmYY4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cWNIa0d5UnpDZDhhK0s0
            Q3dLanpxYVhVZitQRnNubEZUdFhqZlVoTmxvCncyZVVDSFYxaFY2ZG11RXRHMk5h
            aXVHMlhxMkhPUG5TQzRZc01IQlBuczAKLS0tIEY0SEJHOUhiZGw0eUdvWjhuS0Zz
            Q1QxL3h5SUhHT0drTkR6RXJ1amY5RnMKsUD9yzlHFCMcXu0yMQ8wW2SthjI6OUXv
            omPMzCFrCC5xA/I7OFcCN8DkbHT5ya0XOIjxTcRh/YkBAe8Wa5Vu/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QlJNOVJIT1kxS3c2a0pq
            cjRKcC90TTNwSGZ2S013WHUyTFRjZzloaFhvClZzT3Mxc3ljT1VlSXJpa3U2MktJ
            Uk1RRWUvZ2JlcVNQdlkxRXZzSEdlcGsKLS0tIEZwQ2dpaWVlQVZhSUdBV0pycE4w
            YUdzMWF0Qlk0eTBCK3hkd0pXYmFBZTAKqlmaDKfUb4SfNF9zDvICrmhkV4a/bibF
            rZ7LkA41Va0Kxn+XVomIoWt7BOeLfmbW1kHah3hHMA+SLgYDxxJZWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y54qgey5kd66rtadzwck29pmu8dz78wgdymkcdf84kpprs5d634qwswgt7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-08-11T20:32:05Z"
    mac: ENC[AES256_GCM,data:+i4FgLQ1dHAsrxOCnaOjlJBgfFbarco7cG2CWm7kzyIPybXW+7906KEMWul1yvyZz8/C/Ku6Ie+enJYDahK2XN7avbtJnasxjD3A6tBMLXQNG09d/28b+3o1+K5RAcKvU/IfF9t7p2fUwnQNLsM+hy4rK1THIPVz27luLlnVafI=,iv:h3mspbumnGQDaszb8bGas+8d4tkvX91zZJ37216kTcY=,tag:MQxpu/WIWoK1bFhhmfOstA==,type:str]
    version: 3.10.2
