---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-networking-unbound
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./cluster/apps/networking/unbound/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-networking-powerdns
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: unbound
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 5m
