# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:vL69y5k=,iv:53bBm94goKjm4JMXoMWdebNp+8sIfuDfrhEHInlDR+M=,tag:AFsW/3PZ0hmNDnLl2YMaPQ==,type:str]
    admin-password: ENC[AES256_GCM,data:BJw/dbbLUV1E,iv:E+ew7t7+4Wd9MaLnw2B+wWjaUFQOloyqzSfK/4SUX4E=,tag:z5kC5hJ5jKMlAPQL8USCwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bDhEQVhmbmJnbDFrVU53
            cGRQUmFKcFJBOGZkeVhuR0hWQVk1OGNrR3o4ClVra0NMUlBya1kzcmVmM3l3QXVS
            blc4aTlEUG5yZXhNc1VIWkhqb3grQ3cKLS0tIEtiY2FIaEdpTkUvRnI0N0JkVzR6
            RWpEdVh0UUlibkVCZnAxV1M3cXhYam8KXuFvjWGBlz+HS08WCZwYos83nYLwwDC4
            Ct5xwoszLtSoHV1yhVruIcRnH2AuGw68ecooW9k2BZ4CSPi/Zoc7Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRTdxVCtZYklYbVIwYWU2
            bUZNME96R1EvVjNxcHlMdTh2R0xZcFJuR2lBCnh3anAvM09BVUc3QTBDQVhZSmN3
            dldvNk5waXpxdHd4QmN0bHRMLzI4b1UKLS0tIE81NTIyalVYSms5Wng4c1U4N1Zk
            SE90K1VlbVNSRXE2TkRORzJNUHdIR00KbHR4vjqJe/hyEGmfxijGydFyJwfVziMK
            p/Qm8I4tsj3jaLFsE0M1Yhp9R4K0RgnI5o/FuzwKQaDe9CUQrwoMGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bm9PRWhZM2FIbDRLWWNB
            cW10SWk0eFU3WDBWdHk1alBHRlFjcm54SVFNCjZQYVV0YkhKVFdKeWNxaWUyTzR2
            SUM4a3RRQ2RRR3Z5L1h5TXpoVVFxNVUKLS0tIGVJeWNLL0hFRmNLd3oyNUk5MWph
            SDZwc2tIZWtlSzdGZStXQ2dGN3JFKzgK7l5DYIlQZ/JOD2f7Hj+6eG5jfuB+OP/a
            AEtMPoY/dtjoIAQTCjesSIlz+9y2EkBAm6XA127o7VRRB/EonmewZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y54qgey5kd66rtadzwck29pmu8dz78wgdymkcdf84kpprs5d634qwswgt7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-08-11T20:09:34Z"
    mac: ENC[AES256_GCM,data:C5AcHtzBZsG2Z9Q349/LDCi5kxQBi44gKWSmFwGVLuEXAoJh3xCqR/+a5ZT5oc+zxaM18STlKKh+LPXm7hIF8kq7MkSriOFByvnc62E/2QBW3812TvJNeKApH1fQOlOKuMtkIKNyn2T6ygds+T/r5WtO0A02hLGlg2OBU+ABteM=,iv:OPYMwErf6wINE57Mfx83ZMuMY0mAoAxwu+BUoRyOC5c=,tag:XagmsstZ+cSiJhMPLUNKrA==,type:str]
    version: 3.10.2
