---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app tailscale-operator
  app.kubernetes.io/instance: *app
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - local-network-connector.yaml

