apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
stringData:
    client_id: ENC[AES256_GCM,data:eccnnufTsJkMEYwEzd0G4sM=,iv:OKcaJLPdXLwbNfFcK4g8ECAWdCxTkozYMUDECuvkTx4=,tag:Tyb2KCk1xzgKqfG3cKtejA==,type:str]
    client_secret: ENC[AES256_GCM,data:NR4zYcOsev8iDM+6x0neFTREW3ImuI5BLiPu/4H9a+K2nNWCAY0Ek8QEm4UlKdTMEYa13ArU+r4+dtzhw3tvmA==,iv:/4Q6ZxrwFfD4R9QsTVgL6y2HUd51cxr/3U0vEuknxf8=,tag:ng/DHXqKjB7gp+RugyRTsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGU21ROEhGMUVRVkRCMHRu
            WlZiekpKWSsvRGdNcUdaSitHS2t3TlB5dVRjCklQQmRlVVYvNWJaejQxK2lSZDlp
            bVczRmFIbUcyWE5kVk5oWnYzMEdqQ0EKLS0tIGVSOVFCc0Q4d2hzMVJHUkw5cXlv
            TEd5SnZ2b3BnSTlyOUorOHI4Q29iZ2sK5Sp4C5Bmah6oL8hrQ1I438avlNUnQceN
            XB5L8Ns9uGGWuI+nIoc7xrl6ZZRMZtK3pItlRG93PbOr7GoMOyOA/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZjVIK3h3MTZhOFc4WjV5
            b2VDODBGakZrZVZwTzhQT0JVNmpveGQvdTJBCnZXdCt3M0cxS1NLanpnd21FOXQ4
            VmFFMzltMkhYYzJLWVFjbEJhM3AybDAKLS0tIExWd3EvS3dHQmtQS1ZmWTBNOWdI
            SXBJb3FlbVRCN1lUTGFaM3h5UmgwQk0KXwXPGwNS4NRtLN43UNr4P1sb9Lhd+Ynj
            AioD0p8wDylH72Yfoe/bAMeHUyfROQJLvVkHO4mcEqezzQKp98hySA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WTRZTlZqNmgya2VaTjlB
            eTM1U2RVaHNQM3hydWo0UWdqSTZGQnFydlE0CmZubTRxWUVCRHlqYTVEaE1MbHFi
            Sk1Ea1RDMDBpby82dkV6aXBEVFZtY0kKLS0tIGluekN3K1daL3IwSithZjR1NG1F
            U04zQkY3WmtDbnVETmRjcW12R2ZKM3MKeV7akyJaYQL8mVjxA2Z+TZUoTXRp+fBq
            KUDQPU2tghiNVZ6nr5q2lOwBA815u4nyBkLUm4jjceyfJGwvkSIBuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y54qgey5kd66rtadzwck29pmu8dz78wgdymkcdf84kpprs5d634qwswgt7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2024-09-13T22:30:12Z"
    mac: ENC[AES256_GCM,data:EC7APRDUyvU/8F7EyWkA5l6x3YLB/Zav9PURETe33oIjxh+g2OMQspK4+zviK6Yn186Kz+g4cP3JWtmDN3JShjZ/bm214jNeaGpGekRpuYr0ayC4iTFhzdoZEXUZ2zZoO4ejfN842X3nfyHLZylO//+IVqo9jKVGUovQju2GcMA=,iv:MeVz7u24ipzHn59T/tL4gHkATDLiHYFPqzrLNcDBBOY=,tag:73zkQWHxqKmtIfH7xZCfOQ==,type:str]
    version: 3.9.0
