apiVersion: v1
kind: Secret
metadata:
    name: powerdns-admin-secret
    namespace: networking
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TF4NW2b7onNnFiYAIzzItYJ6reZJedYrt34TDVQe8vJRSVG5w+k7GKzyXKe3+t5M,iv:FHPBuTG5nacLDz/K13hPzCKAXlOcGXzWd53VvSrfduA=,tag:2JS3QuS3L3e9RRFEZT5XYQ==,type:comment]
    #ENC[AES256_GCM,data:5dw4Q/sTIMlINBpuSFK5rkk06CNmPs5cQHGGNQwSAJG2GJiqhMAOwbItpWd9NfZwwLvzmw7HkjtCHg==,iv:76rMsL9R5m+6cipBkIEfeydJgYgpsqtT0hNYy16/hiA=,tag:lNjO41GcuqSKq38nYlQjCg==,type:comment]
    database-uri: ENC[AES256_GCM,data:6xenn3GykPPdVpvcYkv9ZKEY9XYAKn592RQ9dxUR8Vqr9znt6CDO0nOhHu3wjSJLJ3g4x2zCy/EO6iDSF33jbIjho8LOMftA0wSaZYPZtTUincpJFpZlAvGk4QnAN7w4WSZwguCjOPsbzZmobD5KGBoGeqs5/RpfxCa7goRKdaeeTa+YhxTGRqI+9BMPy4kS0RRX6JKp9aH8dpfOxcbkgg==,iv:lKDABH0x2E6CdKcgYyBXRek14yJ+x4OZwLyw5HZw87Q=,tag:0/S8DA9kboxzCSmqhWaFXQ==,type:str]
    #ENC[AES256_GCM,data:tFSabr3ADnzjB+NOtBvkpGLBMzo1A5w4hQQMw4XmG99aDDkONiHXdtgLWMryyDh+o1IO8Jk9smy8JH6hcvdh+LbPQf+WRjoFlvjdwbr9GKQEBqLVsv3mU9x2kTOyUmwIjaFfihn8smvc,iv:bsdU+DC8IspAvQRDmToEW2duluRRuRb+KPINZiYQ+sY=,tag:d9ETUYM5ipN35uD26Oqzpg==,type:comment]
    secret-key: ENC[AES256_GCM,data:nQ9jJFI8qzZLa7t3E+noMa7MyZ8/Vv2ZOeZDf2LPDR58CU8dc3NdM5+9p9p9k4+q8+rMNVZ+4SZe0ID2WhxGug==,iv:USLuuf6Yi6sGY7nOjbZ0s7vKqfuWQv3QqyLNlySpQaY=,tag:S/hUY0t6ZL/98KM2TXsSSg==,type:str]
    #ENC[AES256_GCM,data:HSCoAOMGJbPQYeFquu4z86f2yBhkhHQZUhSGY6VUbK+d+8Vow/bwJkRNM5Qp+ikeGAnzXP0s8OqLlAOW5wZvtcaJ,iv:UPo9Ry2qf+sOxmysshAcadfug+dTLTnvlwUuG4WqKK0=,tag:ZAjQpZWP/7giSyACr+xLXQ==,type:comment]
    db-password: ENC[AES256_GCM,data:4VLpNQFGEj7UNEi4aE9tEcobT3qNUE4HIq7FgGF7RJaoiCO6NQ47q2itRxYtRehY5FXVYUAr+T/BLsztZxmEow==,iv:eL0O8dn2PEYCc2uXpL0xSNtTFcG5f6KqJ9WGVAKFsg4=,tag:NnWcbsCfBdncGZ7kRoIO1g==,type:str]
sops:
    age:
        - recipient: age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WDd2RGwvbXF0N2FUM0Nj
            VnRpQWZMSkNjNkUwVStLUTJhelZFVEVSOVJvCmIyOExwUnpCZkhCVzdRbWpjeXlo
            elFnTzFPWXJDZnNsb0R5Q2pHanBadTgKLS0tIFRQeGllT3pOTmhPTHA5Wm9qN3Jj
            dCtJdFpiTkhzTC8zczRkYlpYQVJVTXMKoYeRd85xIe84RBMsRIgMP98N0BmCISzX
            HMVtA3PaDb0TXvj6TVA6bryBu0y7MInQMUt503MwAiS/b3lPbuNtnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vlnldnfdj72qmqg9shtf4q8kzh890g7f4wkuzqw4vaj4ja3hnp2su7eh47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM0t3cWZ2dWEyQWxHNU1L
            V21ieVFXa2t3RDlqTmN2dW5UN214V0ZrbDFrCnhOQU5mVWVNSnRiN2czTUowLzhH
            YkliQVhJSThVZkw4SHZZRkRmN0VMWncKLS0tIDhxUlpnYk0vNENYZlp6K05sNlVF
            WDNhdm1FZ1dHOGQycDhoR0pCYXFoeWMKbte7EQqYzCd3Eel+Z5PRm8a0P1kIfpCe
            pST06nHlT/bpiMqVT/mJXYv6ezXWqyZ11UBwyKF+f6o5UXsRQm0UmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T14:58:48Z"
    mac: ENC[AES256_GCM,data:uYkUb+g9foZsnCaY/bEwKj+diE22sxOInR3ydbbmJDgzi5ki2iisa9dVY69HAfnU8OEWeYxbKoFnIik9nZEmsAc9WFkxUzEFCWtckDjdUk6UDmDZWzkMt1Z9+ogj6HzW4d3D0UztYyHMmODdd/ZcSYgNsDPxjdEySgTcT6LAS7k=,iv:TXmvoOwOHc1moG7PEqyiyAkfMvBOqKyzlIr32cp7jSo=,tag:FWw6go9uMinl/ORU/4IUFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
